/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    NotFound: typeof import('./components/NotFound.vue')['default']
    PostCard: typeof import('./components/PostCard.vue')['default']
    PostCreate: typeof import('./components/PostCreate.vue')['default']
    PostDelete: typeof import('./components/PostDelete.vue')['default']
    PostEdit: typeof import('./components/PostEdit.vue')['default']
    PostEmpty: typeof import('./components/PostEmpty.vue')['default']
    PostForm: typeof import('./components/PostForm.vue')['default']
    PostList: typeof import('./components/PostList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
